#ifndef WESTERNSUPPORT_GLOBAL_H
#define WESTERNSUPPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WESTERNSUPPORT_LIBRARY)
#  define WESTERNSUPPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WESTERNSUPPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WESTERNSUPPORT_GLOBAL_H
