usr/share/glib-2.0/schemas/
usr/share/maliit/plugins/com/ubuntu/images/
usr/share/maliit/plugins/com/ubuntu/keys/
usr/share/maliit/plugins/com/ubuntu/languages/
usr/share/maliit/plugins/com/ubuntu/styles/
usr/share/maliit/plugins/com/ubuntu/Keyboard.qml
usr/share/maliit/plugins/com/ubuntu/KeyboardContainer.qml
usr/share/maliit/plugins/com/ubuntu/WordRibbon.qml
usr/share/maliit/plugins/com/ubuntu/api_tests.qml
usr/share/maliit/plugins/com/ubuntu/constants.js

